name: Release Version and Changelog
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to see previous tags for changelog

      - name: Update Version Files
        run: |
          NEW_VER=${GITHUB_REF#refs/tags/}
          echo "$NEW_VER" > VERSION
          sed -i "s/^VERSION=\"v.*\"/VERSION=\"$NEW_VER\"/" kubectl-migrate

      - name: Generate Changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Add version files and the updated CHANGELOG.md
          git add VERSION kubectl-migrate CHANGELOG.md
          
          # Only commit if there are changes
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: release ${{ github.ref_name }} [skip ci]" && git push origin main)
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
            body: ${{ steps.changelog.outputs.changes }}
            files: |
                kubectl-migrate
                install.sh